
pipeline {
     agent {
         node {
             label 'dev-server'
         }
     }
     environment {
         APP_NAME = "curriculum-skills"
         MAJOR_RELEASE = 0.1
         DOCKER_TAG = "${MAJOR_RELEASE}.${env.BUILD_NUMBER}"
         DOCKER_REG = "harbor.skillab-project.eu"
         DOCKER_REPO = "/skillab-all/"
         DOCKER_REG_CREDS = "harbor-creds"
     }
 
     stages {
         // *************************
         // *** IMAGE BUILD STAGE ***
         // *************************
         stage("Build_Docker_Images"){
             steps {
                 echo "***** Building Docker Image *****"
                 sh 'DOCKER_TAG=test docker compose build'
             }
         }
 
         // ****************************
         // *** Push Images In Harbor ***
         // ****************************
         stage("Push_Image"){
             when {
                 environment name: "GIT_BRANCH", value: "origin/main"
             }
             steps {
                 withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: "${DOCKER_REG_CREDS}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]){
                     echo "***** Push Docker Image *****"
                     sh 'docker compose build'
                     sh 'docker login ${DOCKER_REG} -u ${USERNAME} -p ${PASSWORD}'
                     sh 'docker image push ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}'
                     sh 'DOCKER_TAG="latest" docker compose build'
                     sh 'docker image push ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:latest'
                 }
             }
         }
         
         // **************
         // *** Deploy ***
         // **************
         stage("Deployment"){
             when {
                 environment name: "GIT_BRANCH", value: "origin/main"
             }
 
             steps {
                 withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: "${DOCKER_REG_CREDS}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]){
                     echo "***** Deploy Application *****"
                     sh 'docker login ${DOCKER_REG} -u ${USERNAME} -p ${PASSWORD}'
                     sh 'docker compose pull'
                     sh 'docker compose up -d'
                     sh 'docker ps'
                 }
             }
         }
     }
     post{
         failure{
             // slackSend (color: "#FF0000", message: "Job FAILED: '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
             sh 'docker image rm ${APP_NAME}:test &> /dev/null || true'
             sh 'DOCKER_TAG=test docker compose down --rmi all'
         }
     }
 }